### ISSUE TITLE
titleタグに属性が付いているページではタイトルが取得できない

### ISSUE THREAD

**Issue by 4oi** [ucchyocean/MintChatBot#16]
[ここの](https://github.com/ucchyocean/MintChatBot/blob/master/src/main/java/com/github/ucchyocean/chatbot/URLResponcer.java#L26)正規表現が，属性付きtitleタグにマッチしないためか，[Gyazo](https://gyazo.com)などのサイトではタイトルの取得に失敗した旨が表示されます．

```
.*<title(?: [^>]*)?>([^<]*)</title>.*
```

のような正規表現が良いのではないでしょうか?

**Comment by ucchyocean** [comment]
確かに、タイトルタグの正規表現もそうなんですが、そもそもGyazoに繋がらないですね・・・？
もうちょっと調べてみます。

<pre>
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:190)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1747)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1708)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1691)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1222)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1195)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:379)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:318)
    at com.github.ucchyocean.chatbot.URLResponcer.getURLTitle(URLResponcer.java:129)
    at com.github.ucchyocean.chatbot.URLResponcer.main(URLResponcer.java:264)
Caused by: java.lang.RuntimeException: Could not generate DH keypair
    at com.sun.net.ssl.internal.ssl.DHCrypt.<init>(DHCrypt.java:114)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:559)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:186)
    at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Handshaker.java:593)
    at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Handshaker.java:529)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:943)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215)
    ... 8 more
Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 1024 (inclusive)
    at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DashoA13*..)
    at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:627)
    at com.sun.net.ssl.internal.ssl.DHCrypt.<init>(DHCrypt.java:107)
    ... 15 more
</pre>

**Comment by 4oi** [comment]
すいません，ちょっと見かけた時にふとおもった程度だったので，あんまり検証できていませんでした...
お願いします

**Comment by ucchyocean** [comment]
どうやら、Java6で実行したらうまく動かないようです。Gyazoで使用しているhttpsの暗号化の仕組みが新しすぎて、httpsコネクションを貼るのに失敗するようです。
Java7以降で実行したら問題ありませんでした。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
![2015-12-13_21 09 55](https://cloud.githubusercontent.com/assets/2563444/11766916/63f4168e-a1de-11e5-887c-04e53dddb2cc.png)

**Comment by 4oi** [comment]
ありがとうございました
