### ISSUE TITLE
repeatSignals設定をfalseからtrueに変更して /chatbot reload コマンドを実行すると例外が発生する

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/MintChatBot#21]
config.ymlで、repeatSignals設定をfalseからtrueに変更して、`/chatbot reload`コマンドを実行すると、NullPointerExceptionが発生する。
スタックトレースは以下の通り。
<pre>
[23:23:54] [Server thread/WARN]: Unexpected exception while parsing console command "chatbot reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'chatbot' in plugin MintChatBot v2.5.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:708) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:443) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:407) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at com.github.ucchyocean.chatbot.TimerTask.cancelAllNotifies(TimerTask.java:121) ~[?:?]
	at com.github.ucchyocean.chatbot.MintChatBot.reloadAllData(MintChatBot.java:350) ~[?:?]
	at com.github.ucchyocean.chatbot.MintChatBot.onCommand(MintChatBot.java:165) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
	... 8 more
</pre>

**Comment by ucchyocean** [comment]
Fixed. 動作確認OK
